[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002EF0B7F8150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8ad7edefd5718acfd7ac6da22468c3a4/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002EF0B7F9F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8ad7edefd5718acfd7ac6da22468c3a4/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002EF0B7FB110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8ad7edefd5718acfd7ac6da22468c3a4/element